config/routes.rb
DateIdeas::Application.routes.draw do
  get "errors/404"

  get "errors/500"

  resources :datecarts do
    member do
      delete "clear_cart"
      get "begin_complete"
      put "complete"
      get "email"
      get "print"
      get "calendar"
      get "download_calendar"
      get "subscribe"
    end

    resources :cart_items do
      collection do
        post "create_event"
      end
    end
  end

  namespace :dashboard do
    resource :significant_dates
  end

  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :wizard do
    collection do
      get "search"
    end
    get :autocomplete_neighbourhood_postal_code, :on => :collection
  end

  resources :profiles

  resources :authentications

  resources :relationships, :only => [:create, :destroy]

  resources :businesses

  resources :neighbourhoods

  root :to => "wizard#index"

  match "dashboard/" => "dashboard#index"

  resources :data_farmers do
    collection do
      post "farm"
    end
  end
  match 'data_farmers/update_neighbourhood_select/:city', :controller=>'data_farmers', :action => 'update_neighbourhood_select'
  
  match '*a', :to => 'errors#404'
  
end

app/models/business.rb
class Business < ActiveRecord::Base
  PRICE_RANGE = {'budget' => ['0', '< $10', '$10-$25'],
                 'moderate' => ['$25-$50'],
                 'high_roller' => ['$50+'],
  }
  cattr_reader :per_page
  @@per_page = 10

  has_many :cart_items
  has_many :business_categories
  has_many :categories, :through => :business_categories
  has_many :business_neighbourhoods
  has_many :neighbourhoods, :through => :business_neighbourhoods

    # before_destroy :ensure_not_referenced_by_any_line_item
  validates_presence_of :name, :address1, :province, :city, :postal_code, :phone_no
  validates_length_of :name, :minimum => 4
  validates_length_of :address1, :postal_code, :minimum => 5
  validates_length_of :phone_no, :minimum => 10

  attr_accessor :distance, :avg_rating, :rating_img_url, :reviews, :map, :text_excerpt, :group_date_friendly,:takes_reservations, :hours, :kids_friendly, :gmaps, :has_yelp_data, :review,
:review_count

  def init
    @reviews = []
    @has_yelp_data = false
  end

  def add_review(review)
    @reviews.push(review)
  end

  def display_address
    d_address = address1
    d_address << ", #{address2}" if address2
    d_address << ", #{city}, #{province}"
  end

  # hook method
  def ensure_not_referenced_by_any_line_item
    if cart_items.count.zero?
      return true
    else
      errors.add(:base, 'Cart Items are present')
      return false
    end
  end

  acts_as_gmappable :process_geocoding => false, :validation => false

  def gmaps4rails_address
    display_address
  end

  def gmaps4rails_infowindow
    # add here whatever html content you desire, it will be displayed when users clicks on the marker
    "#{self.name}<br/>#{self.display_address}<br/>#{self.phone_no}"
  end


  def Business.search_by_district_subsection(city, district_subsection, price_point, categories, page, per_page)
    msg="city:%s district subsection:%s price point:%s categories:%s page:%s" % [city, district_subsection, price_point, categories, page]
    Rails.logger.info msg
    sql = ''
    sql <<
        "SELECT b.*                                  \
      FROM                                         \
        businesses b                               \
      WHERE                                        \
            b.dna_pricepoint IN (?)                \
        AND (b.deleted IS NULL OR                  \
             b.deleted = ? )                       \
        AND EXISTS ( SELECT 1                      \
               FROM business_neighbourhoods bn     \
                    ,neighbourhoods n              \
               WHERE n.id=bn.neighbourhood_id      \
                 AND bn.business_id=b.id           \
                 AND n.district_subsection=?       \
                 AND n.city=? )                    \
        AND EXISTS ( SELECT 1                      \
               FROM business_categories bc         \
                    ,categories c                  \
              WHERE c.id=bc.category_id            \
              AND bc.business_id=b.id 	           \
              AND (c.name IN (?) OR                \
                   c.parent_name IN (?) OR
                   c.parent_name IN ( SELECT 1                      \
                                        FROM categories c1          \
                                       WHERE c1.parent_name IN (?)) \
                  ))                                                \
      ORDER BY b.name"
    db_businesses = Business.find_by_sql([sql,
                                          PRICE_RANGE.fetch(price_point),
                                          false,
                                          district_subsection,
                                          city,
                                          categories,
                                          categories,
                                          categories]).paginate(:page => page, :per_page => per_page)
    return db_businesses
  end

  def Business.search_by_neighbourhood(city, neighbourhood, price_point, categories, page)
    msg=" city :% s neighbourhood :% s price point :% s categories :% s page :% s " % [city, neighbourhood, price_point, categories, page]
    Rails.logger.info msg
    sql = ''
    sql <<
        " SELECT b.*                                  \
    FROM                                         \
        businesses b                               \
      WHERE                                        \
            b.dna_pricepoint IN (?)                \
        AND (b.deleted IS NULL OR                  \
             b.deleted = ?)                       \
        AND EXISTS (SELECT 1                      \
               FROM business_neighbourhoods bn     \
                    , neighbourhoods n              \
               WHERE n.id=bn.neighbourhood_id      \
                 AND bn.business_id=b.id           \
                 AND n.neighbourhood= ?             \
                 AND n.city= ?)                    \
        AND EXISTS (SELECT 1                      \
               FROM business_categories bc         \
                    , categories c                  \
              WHERE c.id=bc.category_id            \
              AND bc.business_id=b.id              \
              AND (c.name IN (?) OR                \
                   c.parent_name IN (?) OR
    c.parent_name IN (SELECT 1                      \
                                        FROM categories c1          \
                                       WHERE c1.parent_name IN (?)) \
                  ))                                                \
      ORDER BY b.name "
    db_businesses = Business.find_by_sql([sql,
                                          PRICE_RANGE.fetch(price_point),
                                          false,
                                          neighbourhood,
                                          city,
                                          categories,
                                          categories,
                                          categories]).paginate(:page => page, :per_page => 8)
    return db_businesses
  end

  def Business.search_by_postal_code(city,postal_code, price_point, categories, page)
      puts "search_by_neighbourhood(#{city}, #{postal_code},#{price_point},#{categories},#{page})"
      sql = ""
      sql <<
      "SELECT b.*                                  \
      FROM                                         \
        businesses b                               \
      WHERE                                        \
            b.dna_pricepoint IN (?)                \
        AND (b.deleted IS NULL OR                  \
             b.deleted = ? )                       \
        AND EXISTS ( SELECT 1                      \
               FROM business_neighbourhoods bn     \
                    ,neighbourhoods n              \
               WHERE n.id=bn.neighbourhood_id      \
                 AND bn.business_id=b.id           \
                 AND n.postal_code=?               \
                 AND n.city=? )                    \
        AND EXISTS ( SELECT 1                      \
               FROM business_categories bc         \
                    ,categories c                  \
              WHERE c.id=bc.category_id            \
              AND bc.business_id=b.id 	           \
              AND (c.name IN (?) OR                \
                   c.parent_name IN (?) OR
                   c.parent_name IN ( SELECT 1                      \
                                        FROM categories c1          \
                                       WHERE c1.parent_name IN (?)) \
                  ))                                                \
      ORDER BY b.name"
      db_businesses = Business.find_by_sql([sql,
                                            PRICE_RANGE.fetch(price_point),
                                            false,
                                            postal_code,
                                            city,
                                            categories,
                                            categories,
                                            categories]).paginate(:page => page, :per_page => 8)
      return db_businesses
  end
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
  validates_presence_of :category_name, :business_id
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!, :except => :show

  def index
   @user = current_user
    current_page = params[:page]
    @businesses = Business.all.paginate(:page => current_page, :per_page => 10)
  end

  def show
    @user = current_user
    @business = Business.find(params[:id])
    @datecart = current_cart
    
    @json = @business.to_gmaps4rails
    @markers = @business.to_gmaps4rails


    scrappy = DateIdeas::ScreenScraper.new()
    scraped_biz_details = {}
    scraped_biz_details = scrappy.get_business_details(@business.external_id)
    if (!scraped_biz_details.nil?)
      @business.hours = scraped_biz_details.fetch('hours')
      @business.takes_reservations = scraped_biz_details.fetch('takes_reservations')
      @business.kids_friendly = scraped_biz_details.fetch('kids_friendly')
      @business.dna_dresscode = scraped_biz_details.fetch('dress_code')
      @business.group_date_friendly = scraped_biz_details.fetch('group_date_friendly')
    end

    if (!@business.external_id.nil?)
      yelp_adaptor = DateIdeas::YelpAdaptorV2.new(false)
      business_detail = yelp_adaptor.business_detail(@business.external_id)
      if (!business_detail.nil?)
        Rails.logger.info("business_detail:" +business_detail.to_s)
        if (!@business.external_id.nil? && (@business.dna_excerpt.nil? ||@business.dna_excerpt.size == 0))
          highest_review = Review.new
          highest_review.rating = 0
          business_detail.reviews.each do |biz_review|
            if (biz_review.rating > highest_review.rating)
              highest_review = biz_review
            end
          end

          @business.dna_excerpt = highest_review.text_excerpt
        end
        @business.reviews = business_detail.reviews
      end
    end

    respond_to do |format|
       format.html { render :layout => 'venue' }
       # format.xml  { render :xml => @post }
    end
  end

  def edit
    @user = current_user
    @business = Business.find(params[:id])
  end

  def new
    @user = current_user
    @business = Business.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @post }
    end
  end

  def create
    @business = Business.new(params[:business])

    respond_to do |wants|
      if @business.save
        flash[:notice] = 'Business was successfully created.'
        wants.html { redirect_to(@business) }
        wants.xml { render :xml => @business, :status => :created, :location => @business }
      else
        wants.html { render :action => "new" }
        wants.xml { render :xml => @business.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @business = Business.find(params[:id])

    @business.neighbourhoods = Neighbourhood.find(params[:neighbourhood_ids]) if params[:neighbourhood_ids]
    @business.categories = Category.find(params[:category_ids]) if params[:category_ids]
    if (params[:deleted])
      @business.deleted = true
    else
      @business.deleted = false
    end

    Rails.logger.info("deleted:" + @business.deleted.to_s)
    if @business.update_attributes(params[:business])
      redirect_to(businesses_path, :notice => 'Venue listing was successfully updated.')
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def business_photo business
    business.photo_url
  end
  
  def display_business_hours(business)
    html=""
    if business.hours.nil?
      ""
    else
      raw(business.hours.join("<br/>"))
    end
  end
  
  def display_dateideas_tips
    html = ""
    
    unless @business.dna_excerpt.blank?
      html << '<div id="di_venue_excerpt" class="di_module_large">' 
      html << raw(generate_ribbon_header(:h3, :"dateideas tips", 17)) 
      html << '<div class="di_module_container">' << @business.dna_excerpt << "</div></div>"
	  end
	  
	  raw(html)
  end

  def display_dateideas_reviews
    html = ""
    
    unless @business.reviews.blank?
      html << '<div id="di_reviews" class="di_module_large">'
      html << generate_ribbon_header(:h3, "reviews", 17)
      @business.reviews.each do |r|
        html << html_for_reviews_in_venue(@business.external_id, r)
    	end
      html << '</div>'
    end
    
    raw(html)
  end
  
  def display_review(business)
    html = ""
    if(!business.review.nil?)
      review = business.review
      html_part = ''
        # TODO: Add review count display here
        # TODO: Display price range
      html_part = <<EOF
        <ul class="yelp_review">
          <li><img src="#{review.rating_img_url}" alt="Yelp Rating"></li>
          <li class="review_list_item_excerpt">#{review.text_excerpt}<a href="http://www.yelp.com/biz/#{business.external_id}#hrid:#{review.id}" target="_blank">Read more</a></li>
          <li class="review_list_item_poster">Posted by <a href="http://www.yelp.com/user_details?userid=#{review.user_id}" target="_blank">#{review.name}</a> on <a href="http://www.yelp.com" target="_blank">Yelp.com</a>
          </li>
      </ul>
EOF
      html.concat(html_part)
    end
    html
  end
  
  def html_for_reviews_in_venue(biz_external_id, r)
        # TODO: Add review count display here
        html = <<EOF
        <div class="yelp_review di_module_container">
    			<div class="user_photo"><img src="#{r.user_photo_url_small}" alt="#{r.name}"></div>
    			<div class="review_info">
      			<ul class="yelp_review">
              <li class="review_list_item_excerpt"><img src="#{r.rating_img_url}" alt="Yelp Rating"></li>
              <li>#{r.text_excerpt}<a href="http://www.yelp.com/biz/#{biz_external_id}#hrid:#{r.id}" target="_blank">read more</a></li>
              <li class="review_list_item_poster">Posted by <a href="http://www.yelp.com/user_details?userid=#{r.user_id}" target="_blank">#{r.name}</a> on <a href="http://www.yelp.com" target="_blank">Yelp.com</a></li>
              <li><img src="/images/reviews_from_yelp.gif" %></li>
              </ul>
    			</div>
    		</div>
EOF
  end
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
	<% if @business.errors.any? %>
	<div id="errorExplanation">
	  <h2><%= pluralize(@business.errors.count, "error") %> prohibited this post from being saved:</h2>
	  <ul>
	  <% @business.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
	<% end %>

	<table>
		<tr><td><%=f.label :name %></td><td><%= f.text_field :name %></td></tr>
		<tr><td><%=f.label :address1 %></td><td><%= f.text_field :address1 %></td></tr>
		<tr><td><%=f.label :venue_type %></td><td><%= f.text_field :venue_type %></td></tr>
	    <tr><td><%=f.label :province %></td><td><%= f.text_field :province %></td></tr>
	    <tr><td><%=f.label :postal_code %></td><td><%= f.text_field :postal_code %></td></tr>
	    <tr><td><%=f.label :country %></td><td><%= f.text_field :country %></td></tr>
	    <tr><td><%=f.label :phone_no %></td><td><%= f.text_field :phone_no %></td></tr>
		<tr><td><%=f.label :categories %></td><td>
          <%= select_tag("category_ids[]",
                         options_for_select(Category.find(:all).collect { |cat| [cat.display_name, cat.id]}, @business.categories.collect {|my_cat| my_cat.id }),
                         {:multiple => true, :size => 4 }) %>
        </td></tr>
        <tr><td><%=f.label :neighbourhoods %></td><td>
          <%= select_tag("neighbourhood_ids[]",
                         options_for_select(Neighbourhood.find(:all).collect { |hoods |[hoods.neighbourhood,hoods.id]},@business.neighbourhoods.collect {|my_hood| my_hood.id}),
                         {:multiple => true, :size => 4 })%>
        </td></tr>
		<tr><td><%=f.label :dna_atmosphere %></td><td><%= f.text_field :dna_atmosphere %></td></tr>
		<tr><td><%=f.label :dna_pricepoint %></td><td><%= f.text_field :dna_pricepoint %></td></tr>
		<tr><td><%=f.label :dna_category %></td><td><%= f.text_field :dna_category %></td></tr>
		<tr><td><%=f.label :dna_dresscode %></td><td><%= f.text_field :dna_dresscode %></td></tr>
		<tr><td><%=f.label :dna_review %></td><td><%= f.text_area :dna_review %></td></tr>
		<tr><td><%=f.label :dna_excerpt %></td><td><%= f.text_area :dna_excerpt %></td></tr>
        <tr><td><%=f.label :deleted %></td><td><%= f.check_box(:deleted) %></td></tr>
	</table>
	<%= f.submit %>
<% end %>

app/views/businesses/edit.html.erb
<!-- Nothing here -->
<%= render 'form' %>

app/views/businesses/index.html.erb
<h1> Venues index </h1>
<%= link_to "Add a new venue/business", new_business_path %>
<table width="100%">
	<tr>
		<td>Name</td>
		<td>Address</td>
		<td>Pricepoint</td>
      	<td>Neighbourhood</td>
		<td>Category</td>
        <td>Has Excerpt</td>
        <td>Deleted</td>
	</tr>

<% @businesses.each do |b| %>
	<tr>
	  <td><%= b.name %></td>
	  <td><%= b.address1 %></td>
	  <td><%= b.dna_pricepoint %></td>
      <td><%= b.neighbourhoods.collect {|hood| hood.neighbourhood}.join(',') %></td>
	  <td><%= b.categories.collect {|cat| cat.name}.join(',') %></td>
      <td><%= (b.dna_excerpt.nil? || b.dna_excerpt.size == 0) ? 'no':'yes' %></td>
      <td><%= b.deleted %></td>
	  <td><%= link_to "Edit", edit_business_path(b) %>
	  <%= link_to "Show", business_path(b) %></td>
	</tr>
<% end %>
</table>
<%= will_paginate @businesses %>

app/views/businesses/new.html.erb
<%= render 'form' %>

app/views/businesses/show.html.erb
<div id="di_venue_header">
	<div class="venue">
	  <%= image_tag business_photo(@business), :width => 50, :height => 50 %>
	</div>
  <h1 class="venue"><%= link_to @business.name, @business.url %></h1>
</div>

<div id="venue_page_top_section">
	<div id="di_venue_map">
		 <%= gmaps({"markers" => {"data" => @markers, "custom_infowindow_class" => "yellow"}, "map_options" => {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 15, "draggable" => true, "detect_location" => false}}) %>
	</div>
	<div id="di_venue_buttons">
		<div id="back_button">
		<%= link_to "Back to results", :back, :class => "function_buttons" %>
		</div>
		<ul>
			<li id="add">
				<%= render :partial => 'shared/add_buttons', :locals => {:business => @business} %>
			</li>
			<li id="print"><%= link_to 'Print', print_datecart_path(@datecart), :class => 'function_buttons', :rel => 'external' %></li>
			<li id="clear"><%= link_to 'Share', '#', :class => 'function_buttons', :method => :delete, :remote => true %></li>
		</ul>
	</div>
</div>

<hr/>

<div id="di_venue_info" class="di_module_large">
	<div class="di_module_container">
		<div style="width:50%; float: left">
			<!-- TODO: put this into display_business_hours method -->
			<table>
				<tr>
					<th>hours</th>
					<td><%= display_business_hours(@business) %></td>
				</tr>
			</table>
		</div>
		<!-- there is no business url -->
		<div id="url" style="float:left"></div>
		<table>
			<tr>
				<th>price point</th>
				<th>dress code</th>
				<th>reservations</th>
				<th>group date friendly</th>
				<th>kid friendly</th>
			</tr>
			<tr>
				<td><%= @business.dna_pricepoint %></td>
				<td><%= @business.dna_dresscode %></td>
				<td><%= @business.takes_reservations %></td>
				<td><%= @business.group_date_friendly %></td>
				<td><%= @business.kids_friendly %></td>
			</tr>
		</table>
	</div>
   
</div>

<hr/>

<%= display_dateideas_tips %>

<%= display_dateideas_reviews %>

<%= content_for :sidebar_right do %>
		<%= render @datecart %>
		<div id="plan_button">
			<%= link_to content_tag(:span, "Plan New Date"), new_datecart_path, :id => "plan_date_button_small" %>
		</div>
<% end %>