config/routes.rb
DateIdeas::Application.routes.draw do
  get "errors/404"

  get "errors/500"

  resources :datecarts do
    member do
      delete "clear_cart"
      get "begin_complete"
      put "complete"
      get "email"
      get "print"
      get "calendar"
      get "download_calendar"
      get "subscribe"
    end

    resources :cart_items do
      collection do
        post "create_event"
      end
    end
  end

  namespace :dashboard do
    resource :significant_dates
  end

  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :wizard do
    collection do
      get "search"
    end
    get :autocomplete_neighbourhood_postal_code, :on => :collection
  end

  resources :profiles

  resources :authentications

  resources :relationships, :only => [:create, :destroy]

  resources :businesses

  resources :neighbourhoods

  root :to => "wizard#index"

  match "dashboard/" => "dashboard#index"

  resources :data_farmers do
    collection do
      post "farm"
    end
  end
  match 'data_farmers/update_neighbourhood_select/:city', :controller=>'data_farmers', :action => 'update_neighbourhood_select'
  
  match '*a', :to => 'errors#404'
  
end

app/controllers/dashboard/significant_dates_controller.rb
class Dashboard::SignificantDatesController < ApplicationController

  # Not sure we need an index, all this info is going to be displayed on the dashboard
  def index
    @user = current_user
    @significant_dates = @user.significant_dates

  end

  def create
    # composed of title, date (time), notes, and user_id
    @significant_date = SignificantDate.create(params[:significant_date])
    flash.notice= "Significant Date #{@significant_date.title} saved."
    render :controller => :dashboard
  end

  def new
    @significant_date = SignificantDate.new
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user = current_user # This is ensured by authenticate_user! in the pre-block of app controller
    @significant_dates = @user.significant_dates
    datecarts = @user.datecarts

    current_datecarts = []
    past_counter = 0

      #If a datecart is in the future, store it for extra processing
      #Randomly select one past date to display to the user
    datecarts.each do |cart|
      if t = cart.datetime
        if t <= Time.now
          past_counter += 1
          @past_datecart = cart if rand(past_counter) == 0 # Give each past date an equal probability of being chosen
        else
          current_datecarts << cart
        end
      end

    end

    # show all upcoming dates (confusing to user if this is not done)
    # however, will need to find better UI to nicely display more than 2 upcoming dates
    current_datecarts.sort_by { |c| c.datetime }
    @upcoming_datecarts = current_datecarts
    # For now, just show the two nearest upcoming dates.
    # 2.times do
    #   @upcoming_datecarts << current_datecarts.pop unless current_datecarts.empty?
    # end

    #@significant_dates = @user.significant_dates
    #  #Need to flush out how to handle significant datecarts, since they'll already be captured above.
    #  #    @significat_datecarts = []
    #  #
    #  #    @significant_dates.each do |date|
    #  #      @significat_datecarts << date.datecarts
    #  #    end
    #
    #@profile = Profile.find_by_user_id @user.id
    #
    #unless @profile
    #  # What do we do here if they haven't completed a profile?
    #  # Why is there a distinction between a profile and a user?
    #end

  end
end

app/helpers/dashboard/significant_dates_helper.rb
module Dashboard::SignificantDatesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def format_date_header date, significant = false, friend = false
    scope = {:scope => [:dashboard, :datecart]}
    if date
      if date > DateTime.now
        if significant
          sym = :upcoming_sig
        elsif friend
          sym = :upcoming_friend
        else
          sym = :upcoming
        end
        # I18n.t(sym, scope) + format_datetime(date, :past => false)
        format_datetime(date, :past => false)
      else
        if significant
          sym = :past_sig
        elsif friend
          sym = :past_friend
        else
          sym = :past
        end
        # I18n.t(sym, scope) + format_datetime(date, :past => true)
        format_datetime(date, :past => true)
      end
    else
      #Choose where they need to go to set the date
      # link_to I18n.t(:no_date_set, scope)
      # Removed the link_to as it throws a "no route matches {}" error
      I18n.t(:no_date_set, scope)
    end
  end
end

app/views/dashboard/_datecart.html.erb
<% id_prefix = "datecart_partial_#{datecart.id}" %>
<div id="<%= id_prefix %>" class="di_module_container dashboard_item">
  <h2 id="<%= id_prefix + "_title" %>" class="datecart_title">
  	<%= format_date_header datecart.datetime, datecart.significant_date_id %>
  </h2>
  <div class="datecart_itinerary">
		<div class="business_static_map">
	      <%= generate_map datecart %>
	   </div>
	  <div id="<%= id_prefix + "_content" %>" class="datecart_places">
	    <% unless (cart_items = datecart.cart_items).blank? #TODO: remove once validations are implemented  %>
	        <%= render :partial => "dashboard/datecart_cart_item", :collection => datecart.cart_items %>
	    <% end %>
	  </div>
	</div>
	
	<fieldset class="datecart_notes">
		<%= render :partial => "datecart_notes", :locals => { :datecart => datecart} %>
	</fieldset>
	
	<div class="datecart_share">
	  <%= render :partial => "datecart_actions", :locals => { :datecart => datecart} %>
	</div>
</div>

app/views/dashboard/_datecart_actions.html.erb
<% size = ParamFile.new.datecart_action_icon_size %>
<ul class="datecart_actions">
  <% unless datecart.cart_items.blank? %>
      <li><%= link_to "Cal", calendar_datecart_path(datecart), :remote => true, :class => "dashboard_action_buttons" %></li>
  <% else %>
      <li><%= link_to "Edit", edit_datecart_path(datecart), :remote => true, :class => "dashboard_action_buttons" %></li>
  <% end %>
  <li><%= link_to "Email", email_datecart_path(datecart), :class => "dashboard_action_buttons" %></li>
  <li><%= link_to "Print", print_datecart_path(datecart), :rel => 'external', :class => "dashboard_action_buttons" %></li>
</ul>

<div id="datecart_<%= datecart.id %>_calendar_dialog" class="dialog"></div>
<div id="di_edit_dialog" class="dialog">Dialog</div>

app/views/dashboard/_datecart_cart_item.html.erb
<% if datecart_cart_item.business_id #If we're dealing with a business%>

    <% @business = Business.find(datecart_cart_item.business_id) %>
    <div id="business_<%= @business.id %>" class="business_item">
      <h6 class="business_title">
        <%= link_to @business.name, business_path(@business) %>
      </h6>
      <div class="business_location">
        <%= generate_unordered_list [@business.address1, @business.city,  number_to_phone(@business.phone_no)] %>
      </div>
    </div>

<% else #If we're dealing with an event %>
		<% # if statement can go here with @event being nil 
			 # handle this for now by testing for nil events 
			%>
			
    <% @event = Event.find(datecart_cart_item.event_id) %>
		<% unless @event.blank? %>
	    <div id="event_<%= @event.id %>" class="business_item">
	      <h6 class="business_title">
	        <%= link_to @event.title, @event.url %>
	      </h6>
	      <div class="business_location">
	        <%= generate_unordered_list [@event.venue_address,  @event.city_name] %>
	      </div>
	    </div>
		<% end %>
<% end %>

app/views/dashboard/_datecart_notes.html.erb
<h6>Notes</h6>
<p><%= datecart.notes %></p>

app/views/dashboard/index.html.erb
<% # Main view of the dashboard  %>
<div id="upcoming_panel" class="di_module_large">
	<%= generate_ribbon_header :h3, "upcoming", 13 %>

	  <% if @upcoming_datecarts.blank? %>
			<div class="di_module_container">
	      <p>No upcoming dates planned.</p>
				<%# skip this because there is already a huge plan new date button %>
	      <%#= link_to "+ Add Something New", wizard_index_path, :class => "datecart_buttons center", :remote => true %>
	      <div id="di_add_to_date" class="dialog"></div>
			</div>
	  <% else %>
		      <%= render :partial => "dashboard/datecart", :collection => @upcoming_datecarts %>
	  <% end %>
</div>

<div id="past_panel" class="di_module_large">
		<%= generate_ribbon_header :h3, "Your Past Dates", 13 %>
  <% if @past_datecart.blank? %>
		<div class="di_module_container">
			<p> No past dates </p>
		</div>
  <% else %>
      <%= render :partial => "dashboard/datecart", :locals => {:datecart => @past_datecart} %>
  <% end %>
</div>

<%= content_for :sidebar_right do %>
	<div id="sig_dates">
		<%= link_to content_tag(:span, "Plan New Date"), new_datecart_path, :id => "plan_date_button" %>
	</div>

	<%# Don't show significant dates because its not implemented yet %>
	<%# render 'dashboard/significant_dates/sig_dates' %>
<% end %>