config/routes.rb
DateIdeas::Application.routes.draw do
  get "errors/404"

  get "errors/500"

  resources :datecarts do
    member do
      delete "clear_cart"
      get "begin_complete"
      put "complete"
      get "email"
      get "print"
      get "calendar"
      get "download_calendar"
      get "subscribe"
    end

    resources :cart_items do
      collection do
        post "create_event"
      end
    end
  end

  namespace :dashboard do
    resource :significant_dates
  end

  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :wizard do
    collection do
      get "search"
    end
    get :autocomplete_neighbourhood_postal_code, :on => :collection
  end

  resources :profiles

  resources :authentications

  resources :relationships, :only => [:create, :destroy]

  resources :businesses

  resources :neighbourhoods

  root :to => "wizard#index"

  match "dashboard/" => "dashboard#index"

  resources :data_farmers do
    collection do
      post "farm"
    end
  end
  match 'data_farmers/update_neighbourhood_select/:city', :controller=>'data_farmers', :action => 'update_neighbourhood_select'
  
  match '*a', :to => 'errors#404'
  
end

app/models/datecart.rb
class Datecart < ActiveRecord::Base
  #destroys all cart_items if Datecart is destroyed
  has_many :cart_items, :dependent => :destroy

  belongs_to :user
  belongs_to :significant_date

  validate :has_info_when_assigned_to_user?

  def location
    items = cart_items
    first_venue = items.first unless items.empty?
    if first_venue
      location = first_venue.business_id ? first_venue.business.address1 : first_venue.event.venue_address
    else
      location = ""
    end
    location
  end

  def cart_empty?
    return true if cart_items.empty?
    false
  end

  def display_datetime
    return datetime.strftime('%Y/%m/%d %I:%M %P') if datetime
    ""
  end

  private

  def has_info_when_assigned_to_user?
    if user_id
      if cart_items.blank?
        @errors.add(:base, "You can't save a datecart without any associated events or venues.") #Add link or something to make that happen
      end
      unless name
        @errors.add(:name, "can't be blank.")
      end
      unless datetime
        @errors.add(:base, "You must choose a time for your date.")
      end
    end
  end
end

app/controllers/datecarts_controller.rb
class DatecartsController < ApplicationController
  include DatecartsHelper
  
  load_and_authorize_resource :except => [:subscribe, :clear_cart, :print]
  
  before_filter :authenticate_user!, :except => [:subscribe, :clear_cart, :print]
  before_filter :owns_datecart?, :except => [:index, :new, :clear_cart, :print]

  def index
    @datecarts = Datecart.all

    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml { render :xml => @datecarts }
    end
  end

  def show
    @datecart = Datecart.find(params[:id])

    respond_to do |format|
      format.html { render :layout => 'dashboard' }
      format.xml { render :xml => @datecart }
    end
  end

  # creates a new datecart for 'plan new date'
  # TODO: Prompt user to save cart if current cart has not been saved
  def new
    @datecart = Datecart.create(:session_id => session[:session_id], :last_access => DateTime.now)
    current_user.update_attribute(:active_datecart_id, @datecart.id)
    session[:datecart_id] = @datecart.id
    
    # redirect user to wizard index to start planning date
    respond_to do |format|
      format.js
      format.html { redirect_to wizard_index_path }
      format.xml { render :xml => @datecart }
    end
  end

  # GET /datecarts/1/edit
  def edit
    @datecart = Datecart.find(params[:id])
    authorize! :edit, @datecart
  end

  # POST /datecarts
  # POST /datecarts.xml
  def create
    @datecart = Datecart.new(params[:datecart])

    respond_to do |format|
      if @datecart.save
        format.html { redirect_to(@datecart, :notice => 'Datecart was successfully created.') }
        format.xml { render :xml => @datecart, :status => :created, :location => @datecart }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @datecart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /datecarts/1
  # PUT /datecarts/1.xml
  def update
    @datecart = Datecart.find(params[:id])

    respond_to do |format|
      if @datecart.update_attributes(params[:datecart])
        format.html { redirect_to(@datecart, :notice => 'Datecart was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @datecart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /datecarts/1
  # DELETE /datecarts/1.xml
  def destroy
    @datecart = Datecart.find(params[:id])
    @datecart.destroy

    respond_to do |format|
      if current_user.profile
        format.js
        format.html { redirect_to(current_user.profile) }
      else
        render :nothing => true
      end
      format.xml { head :ok }
    end
  end

  # datecart/:datecart_id/clear_cart
  # POST
  def clear_cart
    @datecart = Datecart.find(params[:id])
    @cleared_items = []
    unless @datecart.cart_empty?
      @cleared_items = @datecart.cart_items.destroy_all
    end

    respond_to do |format|
      format.js
      format.html { redirect_to(@datecart) }
    end
  end

  # Open the dialog to save a datecart from the search screen
  def begin_complete
    @datecart = Datecart.find(params[:id])
    respond_to do |format|
      format.js { render :save_datecart }
      format.html
    end
  end

  # complete date planning
  def complete
    # User has to be logged in to reach here
    @datecart = Datecart.find(params[:id])
    begin
      params[:datecart][:datetime] = DateTime.parse params[:datecart][:datetime]
    rescue Exception
      params[:datecart][:datetime] = nil
    end

    @datecart.update_attributes(params[:datecart].merge({:user_id => current_user.id}))

    if @datecart.errors.blank?
      redirect_to(:dashboard, :notice => :'Datecart was successfully updated.')
    else
      redirect_to :back, :alert => :"There was an error saving your datecart."
    end
    
    # why Datecart.create(:user_id => ...)?
    # current_user.update_attribute(:active_datecart_id, Datecart.create(:user_id => current_user.id).id)
    
    # Design decision - set the active_datecart_id as the last saved cart
    current_user.update_attribute(:active_datecart_id, @datecart.id)
  end

  def email
    @datecart = Datecart.find(params[:id])
    if current_user
      UserMailer.date_plan_email(current_user, @datecart).deliver
      redirect_to(@datecart, :notice => 'An email of your Date Plan was sent!')
    else
      redirect_to(new_user_session_path)
    end
  end

  # Render print view
  def print
    @datecart = Datecart.find(params[:id])
    respond_to do |format|
      format.html { render :layout => 'itinerary_print' }
    end
  end

  # Render the calendar popup (should only be quered via remote javascript request)
  def calendar
    @datecart = Datecart.find(params[:id])
  end

  # Send the calendar as a file download, native file extensions should then handle everything (i.e. outlook)
  def download_calendar
    @datecart = Datecart.find(params[:id])
    send_data generate_vcalendar(@datecart, :download), :filename => "my_date.ics", :type => "text/calendar"
  end

  # Generate the vcal associated the datecart. Allows calendar programs to query for any updates regularly
  def subscribe
    @datecart = Datecart.find(params[:id])
    render :text => generate_vcalendar(@datecart, :subscribe)
  end

  private

  def owns_datecart?
    #TODO: use the cache
    datecart = current_cart
    return true if (datecart.user_id == current_user.id) || (datecart.session_id == session[:session_id])
    render :template => "/errors/404.html.erb", :status => 404
  end

  # Some samples from eventful for reference
  # ical: 'webcal://eventful.com/toronto/ical/events/nkotbsb-tour-new-kids-block-and-backstreet-boys-/E0-001-035309535-0'
  #outlook: 'http://eventful.com/toronto/ical/events/nkotbsb-tour-new-kids-block-and-backstreet-boys-/E0-001-035309535-0'

  def generate_vcalendar datecart, type
    <<-VCAL
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
METHOD:PUBLISH
PRODID:-//gdi//GetDateIdeas//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:#{format_time DateTime.now}Z
DTSTART:#{format_time datecart.datetime}Z
DTEND:#{format_time datecart.datetime}Z
SUMMARY: Date Ideas: #{datecart.name}
PRIORITY:0
CATEGORIES:DATE
CLASS:PRIVATE
URL:#{request.env["REQUEST_URI"]}
DESCRIPTION: #{datecart.notes}
LOCATION: #{datecart.location}
END:VEVENT
END:VCALENDAR
    VCAL
  end
end

app/helpers/datecarts_helper.rb
module DatecartsHelper
  # display date cart sorted by venue type
  def datecart_saved_status
    if @datecart.user_id 
        "Date plan has been saved."
    else
        "Date plan has not been saved."
    end
  end

  def add_more_link_name(datecart)
    if datecart.cart_empty?
      "Add things to do"
    else
      "Add more things to do"
    end
  end
    
  def display_cart_contents(datecart)
    display = ""

    if datecart.cart_empty?
      display = "You haven't got a plan yet!"
    else
      items = datecart.cart_items
      display_text = { "food" => "Dining", "bars" => "Drinks", "activities_events" => "Activities & Events", "nightlife" => 'Nightlife', 'arts_entertainment' => 'Arts and Entertainment'}

      category_display = {}
      items.each do |item|
        # only display under the first venue_type that an item is classified under
        html_str = "<tr><td>"
        type = item.venue_type
        venue = item.business
        if venue.blank?
          venue = item.event
          venue_name = venue.title
          html_str << link_to(venue_name, venue.url)
        else
          venue_name = venue.name
          html_str << link_to(venue_name, business_path(venue))
        end

        html_str = html_str<< "</td><td>" << link_to(content_tag(:span, "", :class => 'ui-icon ui-icon-trash'), datecart_cart_item_path(datecart, item), :method => :delete, :remote => true) << "</td></tr>"
        if category_display[type].nil?
          category_display[type] = html_str
        else
          category_display[type] << " " << html_str
        end
      end

      category_display.keys.sort.each { |key|
       display << "<p>" << display_text[key] << "</p>" 
       display << "<table>" << category_display[key] << "</table>"
      }
    end
    
    return display
  end

  def format_yahoo_calendar_link datecart
    # "http://calendar.yahoo.com/?v=60&amp;view=d&amp;type=20&amp;title=Eventful:+NKOTBSB+Tour%3A+New+Kids+On+The+Block+and+Backstreet+Boys&amp;st=20110608T193000&amp;desc=&amp;in_loc=Air+Canada+Centre&amp;in_st=40+Bay+Street&amp;in_csz=Toronto,+ON,+"
    url = "http://calendar.yahoo.com/?v=60&view=d&type=20&"
    name = datecart.name || "My Date"
    hash = {
        :title => "Date Ideas: #{name}",
        :st => format_time(datecart.datetime),
        :desc => datecart.notes,
        :in_loc => datecart.location
    }
    url << hash.to_query
  end

  def format_google_calendar_link datecart
    # google: "http://www.google.com/calendar/event?action=TEMPLATE&amp;dates=20110608T193000/20110608T193000&amp;text=Eventful:+NKOTBSB+Tour%3A+New+Kids+On+The+Block+and+Backstreet+Boys+at+Air+Canada+Centre&amp;location=40+Bay+Street,Toronto,Ontario,Canada&amp;details=&amp;sprop=partner:evdb.com&amp;sprop=partneruuid:E0-001-035309535-0"
    url = "http://www.google.com/calendar/event?action=TEMPLATE&"
    name = datecart.name || "My Date"
    hash = {
        :text => "Date Ideas: #{name}",
        :dates => format_time(datecart.datetime) << "Z/" << format_time(datecart.datetime) << "Z",
        :sprop => "website:www.getdateideas.com&sprop;=name:Get Date Ideas",
        :details => datecart.notes,
        :location => datecart.location,
        :trp => "true"
    }
    url << hash.to_query
  end

  private

  # Format times like this <year><month><day>T<hour><min><sec>
  # Requires zeroes in front of values to distinguish different fields, hence the prepend zero calls
  def format_time time
    return "" unless time
    "#{time.year}#{prepend_zero(time.month)}#{prepend_zero(time.day)}T#{prepend_zero(time.hour)}#{prepend_zero(time.min)}#{prepend_zero(time.sec)}"
  end

  def prepend_zero date
    if date < 10
      return "0#{date}"
    end
    date
  end
end

app/views/datecarts/_add_to_calendar.html.erb
<%= generate_ribbon_header :h3, :"Save to your Calendar", 7 %>
<ul>
  <li><%= link_to "Yahoo! Calendar", format_yahoo_calendar_link(@datecart), :border => "0", :alt => "Add to Yahoo Calendar" %></li>
  <li><%= link_to "Google Calendar", format_google_calendar_link(@datecart), :alt => "Add to Google Calendar" %></li>
  <li><%= link_to "Outlook", download_calendar_datecart_path(@datecart), :alt => "Add to Outlook" %></li>
  <li><%= link_to "iCal", {:controller => :datecarts, :action => :subscribe, :id => @datecart.id, :format => :ics, :protocol => "webcal", :only_path => false}, :alt => "Add to iCal" %></li>
</ul>

app/views/datecarts/_common_form_elements.html.erb
<% if @datecart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datecart.errors.count, "error") %> prohibited this datecart from being saved:</h2>

      <ul>
        <% @datecart.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<% if @datecart.user_id %>
    <tr>
      <td style="width:100px"><%= form.label :name %></td>
      <td><%= form.text_field :name %></td>

    <tr>
      <td><%= form.label :datetime %></td>
      <td><%= form.text_field :datetime, :value => @datecart.display_datetime, :readonly => 1 %></td>
    </tr>

    <tr>
      <td><%= form.label :notes %></td>
      <td><%= form.text_field :notes %></td>
    </tr>

<% else %>

    <tr>
      <td style="width:100px"><%= form.label :name %> </td>
      <td><%= form.text_field :name, :value => "My Date", :onclick=>"this.value=\"\"", :style => "color:gray;" %></td>

    <tr>
      <td> <%= form.label :datetime %></td>
      <td> <%= form.text_field :datetime, :readonly => 1 %></td>
    </tr>

    <tr>
      <td><%= form.label :notes %></td>
      <td><%= form.text_field :notes, :value => "Make it special!", :onclick => "this.value=''", :style => "color:gray;"%></td>
    </tr>

<% end %>

app/views/datecarts/_datecart.html.erb
<%# View of the cart shown at the front page %>
<% today = Time.now.strftime('%A %B %d, %Y') %>
<div id="di_datecart" class="di_module">
  <div id="di_new_date" class="dialog"></div>
  <div id="di_add_to_date" class="dialog"></div>
  <div id="di_edit_dialog" class="dialog">Dialog</div>

  <h6>
    <span id="date_title" class="floater">My Date Ideas</span>
    <span class="icon"><%= image_tag 'datecart_pencil_icon.png' %></span>
  </h6>

  <div id="di_cart_front" class="di_module_section">
    <fieldset id="datecart_items" class="datecart">
      <%= render :partial => 'datecarts/datecart_items' %>
    </fieldset>
		<%= link_to 'Clear', clear_cart_datecart_path(@datecart), :class => "muted_buttons", :method => :delete, :remote => true %>
  </div>
  <h6>
    <input type="hidden" id="alt_show_date" class="nofloat" value="<%= today %>"/>
    <span id="date_display" class="date_display">
			<% if @datecart.datetime.blank? %>
				<%= today %>
			<% else %>
				<%= format_datetime @datecart.datetime %>
			<% end %>
		</span>
  </h6>

  <div>
		<p>Notes</p>
    <div id="date_notes" class="editable">
			<% if @datecart.notes.blank? %>
				My date notes:
			<% else %>
				<%= @datecart.notes %>
			<% end %>
		</div>
		
    <div id="di_cart_status">
			<%= datecart_saved_status %>
    </div>

    <fieldset id="functions" class="datecart">
      <%= render :partial => 'datecarts/datecart_functions' %>
    </fieldset>
  </div>
</div>

app/views/datecarts/_form.html.erb
<script type="text/javascript"><%= render :partial => "form_javascript_validations.js.erb" %></script>

<%= form_for(@datecart, :id => "update_date_form") do |f| %>
	<table>
    <%= render :partial => "common_form_elements", :locals => {:form => f} %>
		
			<tr>
				<td></td>
		    <td class="actions">
		      <%= f.submit "Update" %>
		    </td>
			</tr>
		</table>
<% end %>

app/views/datecarts/_form_javascript_validations.js.erb
$(document).ready(function() {
    //show date picker pop up
    $('#datecart_datetime').datetimepicker({
        dateFormat: 'yy/mm/dd', // See format options on parseDate
        defaultDate: +1,
        minDate: 0,
        ampm: true,
        hourGrid: 4,
        minuteGrid: 10
    });

    jQuery.validator.addMethod("letterswithbasicpunc", function(value, element) {
        return this.optional(element) || /^[a-z0-9-.,$()'\"\s&!]+$/i.test(value);
    }, "Simple names only!");

    jQuery.validator.messages.required = "Required";

    $("#edit_datecart_<%=@datecart.id%>").validate({
        rules: {
            "datecart[name]": {
                required: true,
                "letterswithbasicpunc": true
            },
            "datecart[datetime]": {
                required: true
            },
            "datecart[notes]": {
                maxlength: 300
            }
        },
        messages: {
            "datecart[notes]": "Max 300 chars"
        }
    });
});

app/views/datecarts/_save_datecart_form.html.erb
<script type="text/javascript"><%= render :partial => "datecarts/form_javascript_validations.js.erb" %></script>
<%= generate_ribbon_header :h3, :"Confirm Details", 7 %>
<%= form_for(@datecart, :url => "/datecarts/#{@datecart.id}/complete", :id => "update_date_form") do |f| %>
	<table>
    <%= render :partial => "datecarts/common_form_elements", :locals => {:form => f} %>

    <tr class="actions">
			<td></td>
      <td><%= f.submit "Save" %></td>
    </tr>
	</table>
<% end %>

app/views/datecarts/calendar.js.erb
//define config object
<% id = "#datecart_#{@datecart.id}_calendar_dialog" %>
var dialogOpts = {
	title: "Export Date to Calendar",
	modal: true,
	overlay: { 
		background: "url(img/modal.png) repeat" 
	},
	// buttons: {
	// 	"Ok": function() { $(this).dialog("close"); }
	// },
	closeOnEscape: true,
	width: 450,
	autoOpen: false,
	resizable: false,
	draggable: false,
	open: function() {
		//display correct dialog content
		$("<%=id%>").html("<%= escape_javascript(render 'add_to_calendar', :format => :html) %>");
	}
};

$("<%=id%>").dialog(dialogOpts);
$("<%=id%>").dialog("open");

app/views/datecarts/destroy.js.erb
$("#date_plans").html('<%= escape_javascript(render :partial => 'profiles/date_plans', :locals => {:user => @datecart.user }) %>')
$("#datecart_items").html("<%= escape_javascript(render 'datecarts/datecart_items') %>")
$("#number").html("<h1><%= get_num_dates_planned @datecart.user %></h1>")
$("#your_last_date").html("<%= escape_javascript(show_last_date @datecart.user) %>")

app/views/datecarts/download_calendar.cal.erb
<%= "my calendar!" %>

app/views/datecarts/edit.html.erb
<h1>Editing datecart</h1>

<%= render 'form' %>

<%= link_to 'Show', @datecart %> |
<%= link_to 'Back', datecarts_path %>

app/views/datecarts/new.html.erb
<h1>New datecart</h1>

<%= render 'form' %>

<%= link_to 'Back', datecarts_path %>

app/views/datecarts/print.html.erb
<%# render :partial => 'shared/itinerary', :locals => {:datecart => @datecart} %>
<!-- mechanism to return to search results -->

<% id_prefix = "datecart_partial_#{@datecart.id}" %>
<div id="<%= id_prefix %>" class="di_module_container dashboard_item">
	<h2><%= @datecart.name %></h2>
  <h3 id="<%= id_prefix + "_title" %>" class="datecart_title">
  	<%= format_date_header @datecart.datetime, @datecart.significant_date_id %>
  </h3>
	<hr/>
	<h3>Notes</h3>
	<div class="datecart_notes di_module_container" style="margin-top:0px">
		<%= @datecart.notes %>
	</div>
	<hr/>
  <div class="datecart_itinerary">
	  <div id="<%= id_prefix + "_content" %>" class="datecart_places">
	    <% unless (cart_items = @datecart.cart_items).blank? #TODO: remove once validations are implemented  %>
				<% @datecart.cart_items.each do |item| %>
					<div class="itinerary_row">
						<%= render :partial => "dashboard/datecart_cart_item", :locals => {:datecart_cart_item => item} %>
						<div class="business_static_map">
						   <%= generate_map_single item %>
					   </div>
						<hr/>
					</div>
				<% end %>
	    <% end %>
	  </div>
	</div>

</div>

app/views/datecarts/save_datecart.js.erb
// Update all logged in elements
$('#user_nav').html("<%= escape_javascript(render :partial => 'shared/navigation') %>")
$("#datecart_items").html("<%= escape_javascript(render 'datecarts/datecart_items') %>")

// Closes modal dialogs
$('.login_dialog').dialog("close");

<%= raw generate_modal_dialogue(:"datecart_save_dialog", :"Enter Date Details", render('datecarts/save_datecart_form', :format => :html)) %>

// populate notes in the save modal box
notes = $('#date_notes').html();
$('#datecart_notes').attr('value', notes);

app/views/datecarts/show.html.erb
<%# Full display of the cart %>
<p id="notice"><%= flash[:notice] %></p>
<%= generate_ribbon_header :h3, @datecart.name, 13 %>
<%= render :partial => "shared/datecart", :locals => {:datecart => @datecart} %>

<%= link_to edit_datecart_path(@datecart), :remote => true, :class => "function_buttons" do %>
    <span>Edit date plan</span>
<% end %>

<!-- dialog boxes -->
<div id="di_edit_dialog" class="dialog">Dialog</div>
<div id="datecart_save_dialog" class="dialog"></div>
<div id="datecart_<%= @datecart.id %>_calendar_dialog" class="dialog">Calendar Dialog</div>
<div id="di_add_to_date" class="dialog">Dialog</div>