config/routes.rb
DateIdeas::Application.routes.draw do
  get "errors/404"

  get "errors/500"

  resources :datecarts do
    member do
      delete "clear_cart"
      get "begin_complete"
      put "complete"
      get "email"
      get "print"
      get "calendar"
      get "download_calendar"
      get "subscribe"
    end

    resources :cart_items do
      collection do
        post "create_event"
      end
    end
  end

  namespace :dashboard do
    resource :significant_dates
  end

  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :wizard do
    collection do
      get "search"
    end
    get :autocomplete_neighbourhood_postal_code, :on => :collection
  end

  resources :profiles

  resources :authentications

  resources :relationships, :only => [:create, :destroy]

  resources :businesses

  resources :neighbourhoods

  root :to => "wizard#index"

  match "dashboard/" => "dashboard#index"

  resources :data_farmers do
    collection do
      post "farm"
    end
  end
  match 'data_farmers/update_neighbourhood_select/:city', :controller=>'data_farmers', :action => 'update_neighbourhood_select'
  
  match '*a', :to => 'errors#404'
  
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :business
  belongs_to :event
  belongs_to :datecart

  validates :datecart_id, :presence => true
  validate :has_an_event_or_business?

  def type
    return 'event' if business_id.blank?
    return 'business' if event_id.blank?
    'none'
  end

  private

  def has_an_event_or_business?
    @errors.add(:base, "Can't save a cart item unless it has an associated business or event.") unless (business_id || event_id)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  load_and_authorize_resource

  before_filter :authenticate_user!, :except => [:create, :create_event, :update, :destroy]
  
  # GET /cart_items
  # GET /cart_items.xml
  def index
    @cart_items = CartItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @cart_items }
    end
  end

    # Removed show action, we don't really need it

    # GET /cart_items/new
    # GET /cart_items/new.xml
  def new
    @cart_item = CartItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @cart_item }
    end
  end

    # GET /cart_items/1/edit
  def edit
    @datecart = current_cart
    @cart_item = @datecart.cart_items.find(params[:id])
  end

    # POST /cart_items
    # POST /cart_items.xml
  def create
    @datecart = current_cart
    @business = Business.find(params[:business_id])

    if @datecart
      @cart_item = @datecart.cart_items.build(:business => @business, :venue_type => session['venue_type'])
    end

    respond_to do |format|
      if @cart_item.save
        format.js
        format.html
      else
        format.html { render :action => "new" }
      end
    end
  end

  def create_event
    @datecart = current_cart
    @event = Rails.cache.fetch(params[:event_id]) do
      Event.find_by_eventid(params[:event_id])
    end

    @cart_item = CartItem.new(:datecart_id => @datecart.id, :event_id => @event.id, :venue_type=> session['venue_type'])

    respond_to do |format|
      if @cart_item.save
        format.js
        format.html
      else
        Rails.logger.debug "Event cart_item save failed"
      end
    end
  end

    # PUT /cart_items/1
    # PUT /cart_items/1.xml
  def update
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      if @cart_item.update_attributes(params[:cart_item])
        format.html { redirect_to(@cart_item, :notice => 'Cart item was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @cart_item.errors, :status => :unprocessable_entity }
      end
    end
  end

    # DELETE /cart_items/1
    # DELETE /cart_items/1.xml
  def destroy
    @datecart = Datecart.find(params[:datecart_id])
    @cart_item = @datecart.cart_items.find(params[:id])

    if @cart_item.type == 'event'
      @deleted_eventid = @cart_item.event.eventid
    end

    @cart_item.destroy

    respond_to do |format|
      if @cart_item.business_id.nil?
        format.js {
          render :action => "destroy_event"
        }
        format.html { redirect_to(cart_items_url) }
        format.xml { head :ok }
      else
        format.js
      end
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def show_name(cart_item)
    if cart_item.business.nil?
      cart_item.event.title
    else
      cart_item.business.name
    end
  end
end

app/views/cart_items/_cart_item.html.erb
<%# A single item displayed in the date cart %>
<li>
<%= params['venue'] %>
<%= show_name(cart_item) %>
<%= link_to('Remove', datecart_cart_item_path(@datecart, cart_item), :method => :delete, :remote => true) %>
</li>

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/create.js.erb
$("#datecart_items").html("<%= escape_javascript(render :partial => 'datecarts/datecart_items') %>");
$("#add_to_date_<%= params[:business_id] %>").html("<%= escape_javascript(render :partial => 'wizard/remove', :locals => {:datecart => @datecart, :business => @business}) %>");

app/views/cart_items/create_event.js.erb
$("#datecart_items").html("<%= escape_javascript(render :partial => 'datecarts/datecart_items') %>");
$("#event_<%= params[:event_id] %>").html("<%= escape_javascript(render :partial => 'wizard/remove_event', :locals => {:datecart => @datecart, :eventid => params[:event_id]}) %>");

app/views/cart_items/destroy.js.erb
$("#datecart_items").html("<%= escape_javascript(render :partial => 'datecarts/datecart_items') %>")
$("#add_to_date_<%= @cart_item.business_id %>").html("<%= escape_javascript(render :partial => 'wizard/add', :locals => {:datecart => @datecart, :business => @cart_item.business}) %>")

app/views/cart_items/destroy_event.js.erb
$("#datecart_items").html("<%= escape_javascript(render :partial => 'datecarts/datecart_items') %>")
// console.log("<%= @deleted_eventid %>")
$("#event_<%= @deleted_eventid %>").html("<%= escape_javascript(render :partial => 'wizard/add_event', :locals => {:datecart => @datecart, :eventid => @deleted_eventid}) %>")

app/views/cart_items/edit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', datecart_cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Listing cart_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cart_items.each do |cart_item| %>
  <tr>
    <td><%= cart_item.business_id %></td>
    <td><%= cart_item.datecart_id %></td>
    <td><%# link_to 'Show', cart_item %></td>
<!-- edit_datecart_cart_item -->
    <td><%# link_to 'Edit', edit_datecart_cart_item_url(cart_item) %></td>
    <td><%# link_to 'Destroy', cart_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', datecart_cart_items_path %>